import { useState, useEffect } from 'react';
import './index.css';

function App() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [activeCategory, setActiveCategory] = useState('trending');
  const [activeTab, setActiveTab] = useState('trending_daily');

  useEffect(() => {
    // Dynamic import to allow fetching data generated by Action
    fetch(`${import.meta.env.BASE_URL}trending.json`)
      .then(res => res.json())
      .then(json => {
        setData(json);
        setLoading(false);
      })
      .catch(err => {
        console.error("Failed to load trending data:", err);
        // Fallback to empty structure if file doesn't exist yet
        setData({ 
          trending_daily: [], trending_weekly: [], trending_monthly: [], 
          overall_weekly: [], overall_monthly: [], overall_yearly: [], overall_all: [], 
          lastUpdated: null 
        });
        setLoading(false);
      });
  }, []);

  const getLanguageColor = (lang) => {
    const colors = {
      JavaScript: '#f1e05a',
      TypeScript: '#3178c6',
      Python: '#3572A5',
      Java: '#b07219',
      'C++': '#f34b7d',
      Go: '#00ADD8',
      Rust: '#dea584',
      Ruby: '#701516',
      HTML: '#e34c26',
      CSS: '#563d7c'
    };
    return colors[lang] || '#8b949e';
  };

  const categories = [
    { id: 'trending', label: '飙升榜' },
    { id: 'overall', label: '总榜' }
  ];

  const subTabs = {
    trending: [
      { id: 'trending_daily', label: '今日' },
      { id: 'trending_weekly', label: '本周' },
      { id: 'trending_monthly', label: '本月' }
    ],
    overall: [
      { id: 'overall_weekly', label: '本周' },
      { id: 'overall_monthly', label: '本月' },
      { id: 'overall_yearly', label: '今年' },
      { id: 'overall_all', label: '历史总榜' }
    ]
  };

  return (
    <div className="container">
      <header>
        <h1>GitHub Star Board</h1>
        <p>Discover the most exciting open-source projects</p>
      </header>

      <div style={{ display: 'flex', justifyContent: 'center', gap: '1rem', marginBottom: '1.5rem' }}>
        {categories.map(cat => (
          <button
            key={cat.id}
            style={{
              background: activeCategory === cat.id ? 'var(--accent-color)' : 'var(--glass-bg)',
              color: activeCategory === cat.id ? 'white' : 'var(--text-secondary)',
              border: '1px solid var(--glass-border)',
              padding: '0.6rem 1.5rem',
              borderRadius: '100px',
              cursor: 'pointer',
              fontWeight: 600,
              transition: 'all 0.3s ease'
            }}
            onClick={() => {
              setActiveCategory(cat.id);
              setActiveTab(subTabs[cat.id][0].id); // default to first subtab
            }}
          >
            {cat.label}
          </button>
        ))}
      </div>

      <nav>
        {subTabs[activeCategory].map(tab => (
          <button
            key={tab.id}
            className={activeTab === tab.id ? 'active' : ''}
            onClick={() => setActiveTab(tab.id)}
          >
            {tab.label}
          </button>
        ))}
      </nav>

      <main>
        {loading ? (
          <div className="empty-state">Loading repositories...</div>
        ) : (
          <div className="repo-list">
            {data[activeTab]?.length > 0 ? (
              data[activeTab].map((repo, index) => (
                <a 
                  key={repo.id} 
                  href={repo.html_url} 
                  target="_blank" 
                  rel="noopener noreferrer" 
                  className="repo-card"
                  style={{ animationDelay: `${index * 0.05}s` }}
                >
                  <div className="rank">#{index + 1}</div>
                  <img src={repo.owner.avatar_url} alt={`${repo.owner.login} avatar`} className="avatar" loading="lazy" />
                  
                  <div className="repo-info">
                    <div className="repo-header">
                      <div className="repo-name">
                        <span>{repo.owner.login} / </span>
                        {repo.name}
                      </div>
                      <div className="stars">
                        <svg viewBox="0 0 16 16" width="16" height="16" fill="currentColor">
                          <path d="M8 .25a.75.75 0 0 1 .673.418l1.882 3.815 4.21.612a.75.75 0 0 1 .416 1.279l-3.046 2.97.719 4.192a.751.751 0 0 1-1.088.791L8 12.347l-3.766 1.98a.75.75 0 0 1-1.088-.79l.72-4.194L.818 6.374a.75.75 0 0 1 .416-1.28l4.21-.611L7.327.668A.75.75 0 0 1 8 .25Z"></path>
                        </svg>
                        {repo.stargazers_count.toLocaleString()}
                        {repo.growth_stars && (
                          <span style={{ color: '#3fb950', fontSize: '0.85em', marginLeft: '0.4rem' }}>
                            +{repo.growth_stars.toLocaleString()}
                          </span>
                        )}
                      </div>
                    </div>
                    
                    <div className="description">
                      {repo.description || 'No description provided.'}
                    </div>
                    
                    <div className="meta">
                      {repo.language && (
                        <div className="language">
                          <span className="lang-color" style={{ backgroundColor: getLanguageColor(repo.language) }}></span>
                          {repo.language}
                        </div>
                      )}
                    </div>
                  </div>
                </a>
              ))
            ) : (
              <div className="empty-state">
                No repositories found for this period. They will appear here once the daily GitHub Action runs.
              </div>
            )}
          </div>
        )}
      </main>

      <footer>
        {data?.lastUpdated && (
          <div>Last Updated: {new Date(data.lastUpdated).toLocaleDateString()}</div>
        )}
        <div style={{ marginTop: '0.5rem', opacity: 0.7 }}>
          Built with React & Vite. Powered by GitHub Actions.
        </div>
      </footer>
    </div>
  );
}

export default App;
