import { useState, useEffect } from 'react';
import './index.css';

function App() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [activeCategory, setActiveCategory] = useState('trending');
  const [activeTab, setActiveTab] = useState('trending_daily');
  const [lang, setLang] = useState('en');

  useEffect(() => {
    // Dynamic import to allow fetching data generated by Action
    fetch(`${import.meta.env.BASE_URL}trending.json`)
      .then(res => res.json())
      .then(json => {
        setData(json);
        setLoading(false);
      })
      .catch(err => {
        console.error("Failed to load trending data:", err);
        // Fallback to empty structure if file doesn't exist yet
        setData({
          trending_daily: [], trending_weekly: [], trending_monthly: [],
          overall_weekly: [], overall_monthly: [], overall_yearly: [], overall_all: [],
          lastUpdated: null
        });
        setLoading(false);
      });
  }, []);

  const getLanguageColor = (lang) => {
    const colors = {
      JavaScript: '#f1e05a',
      TypeScript: '#3178c6',
      Python: '#3572A5',
      Java: '#b07219',
      'C++': '#f34b7d',
      Go: '#00ADD8',
      Rust: '#dea584',
      Ruby: '#701516',
      HTML: '#e34c26',
      CSS: '#563d7c'
    };
    return colors[lang] || '#8b949e';
  };

  const t = {
    explore: lang === 'zh' ? '探索 (EN)' : 'Explore (CN)',
    create: lang === 'zh' ? '创造' : 'Create',
    creator: lang === 'zh' ? '创作者' : 'Creators',
    heroTitle: 'GitHub Star Board',
    heroSubtitle: lang === 'zh'
      ? '发现全网最激动人心的优秀开源项目'
      : 'Discover the most exciting open-source projects',
    loading: lang === 'zh' ? '正在加载全球排行榜...' : 'Loading global leaderboards...',
    empty: lang === 'zh' ? '该时间段尚未抓取到项目，等待每日自动化爬虫更新。' : 'No repositories found for this period. They will appear here once the daily GitHub Action runs.',
    lastUpdated: lang === 'zh' ? '最近抓取更新：' : 'Last Updated: ',
    footer: lang === 'zh' ? '基于 React & Vite 构建 · GitHub Actions 驱动爬虫' : 'Built with React & Vite · Fully Automated via GitHub Actions',
    noDesc: lang === 'zh' ? '暂无项目描述。' : 'No description provided.',
    rank: lang === 'zh' ? '第' : '#',
    rankSuffix: lang === 'zh' ? '名' : ''
  };

  const categories = [
    { id: 'trending', label: lang === 'zh' ? '飙升榜' : 'Trending' },
    { id: 'overall', label: lang === 'zh' ? '总榜' : 'Overall' }
  ];

  const subTabs = {
    trending: [
      { id: 'trending_daily', label: lang === 'zh' ? '今日' : 'Daily' },
      { id: 'trending_weekly', label: lang === 'zh' ? '本周' : 'Weekly' },
      { id: 'trending_monthly', label: lang === 'zh' ? '本月' : 'Monthly' }
    ],
    overall: [
      { id: 'overall_weekly', label: lang === 'zh' ? '本周' : 'Weekly' },
      { id: 'overall_monthly', label: lang === 'zh' ? '本月' : 'Monthly' },
      { id: 'overall_yearly', label: lang === 'zh' ? '今年' : 'Yearly' },
      { id: 'overall_all', label: lang === 'zh' ? '历史总榜' : 'All-Time' }
    ]
  };

  return (
    <div className="app-wrapper">
      <nav className="site-nav">
        <div className="logo-group">
          <svg width="32" height="32" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M12 2L2 7L12 12L22 7L12 2Z" fill="#2bc0ff" />
            <path d="M2 12L12 17L22 12" stroke="#d23fff" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
            <path d="M2 17L12 22L22 17" stroke="#00F0FF" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
          <span className="logo-text">GITHUB STAR</span>
        </div>
        <div className="nav-actions" style={{ gap: '1.5rem' }}>
          <button className="lang-toggle-btn" onClick={() => setLang(lang === 'zh' ? 'en' : 'zh')}>
            <span className="lang-icon">{lang === 'zh' ? '🇬🇧' : '🇨🇳'}</span>
            <span className="lang-text">{lang === 'zh' ? 'EN' : '中文'}</span>
          </button>
          <a className="sponsor-btn" href="https://www.buymeacoffee.com/JJJIKING" target="_blank" rel="noreferrer">
            <span className="sponsor-icon">☕</span>
            <span className="sponsor-text">{lang === 'zh' ? '请客喝杯咖啡' : 'Buy me a coffee'}</span>
          </a>
        </div>
      </nav>

      <section className="hero">
        <h1 className="hero-title">
          {t.heroTitle}
        </h1>
        <p className="hero-subtitle">
          {t.heroSubtitle}
        </p>
      </section>

      <div id="boards" className="container">
        <div className="category-nav">
          {categories.map(cat => (
            <button
              key={cat.id}
              className={`category-btn ${activeCategory === cat.id ? 'active' : ''}`}
              onClick={() => {
                setActiveCategory(cat.id);
                setActiveTab(subTabs[cat.id][0].id); // default to first subtab
              }}
            >
              {cat.label}
            </button>
          ))}
        </div>

        <nav className="tab-nav">
          {subTabs[activeCategory].map(tab => (
            <button
              key={tab.id}
              className={`tab-btn ${activeTab === tab.id ? 'active' : ''}`}
              onClick={() => setActiveTab(tab.id)}
            >
              {tab.label}
            </button>
          ))}
        </nav>

        <main>
          {loading ? (
            <div className="empty-state">{t.loading}</div>
          ) : (
            <div className="repo-list">
              {data[activeTab]?.length > 0 ? (
                data[activeTab].map((repo, index) => (
                  <a
                    key={repo.id}
                    href={repo.html_url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="repo-card"
                    style={{ animationDelay: `${Math.min(index * 0.02, 1)}s` }}
                  >
                    <div className="rank">{lang === 'zh' ? t.rank + (index + 1) + t.rankSuffix : t.rank + (index + 1)}</div>
                    <img
                      className="avatar"
                      src={repo.owner?.avatar_url || repo.avatar || `https://github.com/${repo.author || repo.owner?.login}.png`}
                      alt=""
                      loading="lazy"
                    />
                    <div className="repo-info">
                      <div className="repo-header">
                        <div className="repo-name">
                          <span>{repo.owner?.login} / </span>
                          <span className="name-bold">{repo.name}</span>
                        </div>
                        <div className="stars">
                          <svg viewBox="0 0 16 16" width="16" height="16" fill="currentColor">
                            <path d="M8 .25a.75.75 0 0 1 .673.418l1.882 3.815 4.21.612a.75.75 0 0 1 .416 1.279l-3.046 2.97.719 4.192a.751.751 0 0 1-1.088.791L8 12.347l-3.766 1.98a.75.75 0 0 1-1.088-.79l.72-4.194L.818 6.374a.75.75 0 0 1 .416-1.28l4.21-.611L7.327.668A.75.75 0 0 1 8 .25Z"></path>
                          </svg>
                          {repo.stargazers_count.toLocaleString()}
                          {repo.growth_stars > 0 && (
                            <span style={{ color: '#3fb950', fontSize: '0.85em', marginLeft: '0.4rem' }}>
                              +{repo.growth_stars.toLocaleString()}
                            </span>
                          )}
                        </div>
                      </div>

                      <p className="description">
                        {repo.description || t.noDesc}
                      </p>

                      <div className="meta">
                        {repo.language && (
                          <div className="language">
                            <span className="lang-color" style={{ backgroundColor: getLanguageColor(repo.language) }}></span>
                            {repo.language}
                          </div>
                        )}
                      </div>
                    </div>
                  </a>
                ))
              ) : (
                <div className="empty-state">
                  {t.empty}
                </div>
              )}
            </div>
          )}
        </main>

        <footer>
          {data?.lastUpdated && (
            <div>{t.lastUpdated}{new Date(data.lastUpdated).toLocaleString()}</div>
          )}
          <div style={{ marginTop: '0.5rem', opacity: 0.7 }}>
            {t.footer}
          </div>
          <div style={{ marginTop: '1.2rem', display: 'flex', justifyContent: 'center' }}>
            <a href="https://hits.seeyoufarm.com">
              <img src="https://hits.seeyoufarm.com/api/count/incr/badge.svg?url=https%3A%2F%2Fjjjiking.github.io%2Fgithubstar&count_bg=%23e81cff&title_bg=%23161B22&icon=&icon_color=%23E7E7E7&title=hits&edge_flat=false" alt="Hits" />
            </a>
          </div>
        </footer>
      </div>
    </div>
  );
}

export default App;
